[build]
  command = "npm run build:web"
  publish = "web-build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  EXPO_USE_FAST_RESOLVER = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  EXPO_NO_MINIFY = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
